### ISSUE TITLE
Ticker no Timestamp

### ISSUE THREAD

**Issue by eRfO** [cassandre-tech/cassandre-trading-bot#544] opened 2021-04-14 20:54 UTC
Hi,
when the Ticker returrned by exchange has timestamp field to null, only the first value is posted to the strategy. This happens because the timestamp on the object is null and in the TickerFlux class there is a check on TickerDTO that compare the previuous timestamp with the new one but the getTimestamp method returns now for both instances.

Maybe you could set the timestamp directly in the mapper when the exchange doesn't.

Thanks,
Michele

**Comment by straumat** [comment] 2021-04-14 20:57
Hi Michele, which release of Cassandre do you use ? 
I thought this was fixed in this issue : https://github.com/cassandre-tech/cassandre-trading-bot/pull/482

**Comment by eRfO** [comment] 2021-04-14 23:19
Hi Stéphane,
I'm using 4.1.1 version of Cassandre, it seems to be the last.

Thank you.

**Comment by straumat** [comment] 2021-04-15 11:35
Which exchange are you using ? do you have any errors in the logs ?

**Comment by eRfO** [comment] 2021-04-15 22:08
I'm using Binance, but seems that the errors is related to TickerDTO equals method. Decompiling code I see this:

`    public final boolean equals(final Object o) {
        if (this == o) {
            return true;
        } else if (o != null && this.getClass() == o.getClass()) {
            TickerDTO that = (TickerDTO)o;
            return (new EqualsBuilder()).append(this.currencyPair, that.currencyPair).append(this.getTimestamp(), that.getTimestamp()).isEquals();
        } else {
            return false;
        }
    }`

so the old code.

Thanks,
Michele

**Comment by straumat** [comment] 2021-04-15 22:10
@eRfO can you should me the first ticker received in your strategy?

**Comment by eRfO** [comment] 2021-04-15 22:14
Yes, I tried to run now and in the console I see:

`New ticker TickerDTO(currencyPair=BTC/EUR, open=52590.25000000, last=53162.91000000, bid=53159.35000000, ask=53162.94000000, high=53404.90000000, low=51961.63000000, vwap=52600.01430987, volume=2713.52616600, quoteVolume=142731515.16180777, bidSize=0.00789300, askSize=0.00156300, timestamp=2021-04-16T00:13:05.207450700+02:00[Europe/Rome])`

**Comment by straumat** [comment] 2021-04-15 22:15
@eRfO Ok, I will create a binance account and make a test.

**Comment by eRfO** [comment] 2021-04-15 22:17
Ok, thank you.

**Comment by Tempys** [comment] 2021-04-16 05:51
@eRfO  have the same issue (

**Comment by straumat** [comment] 2021-04-16 16:03
Hi, @eRfO & @Tempys  I made a test and it's working. Maybe you should change the release number of XChange in your `pom.xml`?

This is what I set:
```
        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-binance</artifactId>
            <version>5.0.7</version>
        </dependency>
```

It works with my [Binance integration test](https://github.com/cassandre-tech/cassandre-trading-bot/blob/280a2e05105438dc711a9acb48f67bd6510ea3e4/spring-boot-starter/autoconfigure/src/test/java/tech/cassandre/trading/bot/integration/binance/MarketServiceTest.java#L104).

**Comment by Tempys** [comment] 2021-04-16 16:09
@straumat  it also works for me in dry mode but does not work when dry mode is false

**Comment by eRfO** [comment] 2021-04-16 16:11
Hi,
@straumat the tests I did already used the latest version of the XChange library, but in the compiled code I keep seeing the equals method of TickerDTO with only currencyPair and timestamp fields. Even as @Tempys I don't use dry mode.

**Comment by Tempys** [comment] 2021-04-16 16:17
@straumat @eRfO basically after updating version to latest version i start get to event but no so often as should be .

**Comment by straumat** [comment] 2021-04-16 16:25
@Tempys it's "normal". In fact, if you ask Cassandre to check tickers every second for example, it does it. But if the server replis with the same value, cassandre will only push data if they are different from the previous one received

**Comment by eRfO** [comment] 2021-04-16 18:30
![image](https://user-images.githubusercontent.com/3831236/115067127-c3d83c00-9ef0-11eb-85be-1e2014170400.png)
 
@straumat as you can see, just only one ticker is emitted by the TickerFlux, I'm using BTC/EUR currency pair in my test.
The ticker rate configuration is set to:

> cassandre.trading.bot.exchange.rates.ticker=PT5S

**Comment by eRfO** [comment] 2021-04-16 18:59
![image](https://user-images.githubusercontent.com/3831236/115071492-9bebd700-9ef6-11eb-9996-4a536defa8fb.png)

Just a question, the above change is in 4.1.1 version?

Thank you.

**Comment by straumat** [comment] 2021-04-16 20:19
@eRfO If timestamp from the server is null the `getTimestamp()` method will return now which will be different from the ticker timestamp so it should make the new ticker  not equal. Can you try` 4.1.2-SNAPSHOT` ? 
My test is working on Binance so it should work for you too.

**Comment by eRfO** [comment] 2021-04-16 20:35
@straumat I tried with the 4.1.2-SNAPSHOT but the result is the same:

![image](https://user-images.githubusercontent.com/3831236/115080986-d740d280-9f03-11eb-8c88-04595ff68b8f.png)

**Comment by Tempys** [comment] 2021-04-16 20:36
@eRfO @straumat the same for me .

**Comment by eRfO** [comment] 2021-04-16 20:45
@straumat, ok, I requested the access to the project source

**Comment by eRfO** [comment] 2021-04-16 20:53
@straumat just tried, the result is the same:

![image](https://user-images.githubusercontent.com/3831236/115082603-7666c980-9f06-11eb-8833-dd8da6487629.png)

**Comment by straumat** [comment] 2021-04-16 20:57
@eRfO you did `mvn spring-boot:run` on my project ?

**Comment by eRfO** [comment] 2021-04-16 21:01
![image](https://user-images.githubusercontent.com/3831236/115083236-5be12000-9f07-11eb-81a1-0b2d186c9bdd.png)

@straumat this is the situation when a ticker is retrieved from binance, the current ticker and the previous one are different but the flux not emit a new ticker to the strategy because both timestamps are null.

**Comment by eRfO** [comment] 2021-04-16 21:02
> @eRfO you did `mvn spring-boot:run` on my project ?

I runned your project with IntelliJ.

**Comment by Tempys** [comment] 2021-04-16 21:04
@straumat i agree with @eRfO  because i got 3 events when prices on binances changed 10 or 30 times per few minutes .

**Comment by straumat** [comment] 2021-04-16 21:05
@eRfO can you suppress the tech directory in your .m2 and run `mvn spring-boot:run` in my project directory ?

**Comment by eRfO** [comment] 2021-04-16 21:21
> @eRfO can you suppress the tech directory in your .m2 and run `mvn spring-boot:run` in my project directory ?

@straumat Yes, I suppressed the tech directory and run `mvn spring-boot:run` the result is the same:

![image](https://user-images.githubusercontent.com/3831236/115084552-62709700-9f09-11eb-8dbe-e334ff385c4c.png)

**Comment by eRfO** [comment] 2021-04-16 21:28
@straumat is this `ZonedDateTime.now().equals(ZonedDateTime.now())` deteministic?

**Comment by straumat** [comment] 2021-04-16 21:29
@eRfO It should be...  what i don't get is how can the result can be different from on my computer and yours... DO you use JDK 11? very strange... maybe we can try to make a live debug tomorrow night on discord ?

**Comment by eRfO** [comment] 2021-04-16 21:36
@straumat I'm using JDK 15 but this code `ZonedDateTime.now().equals(ZonedDateTime.now())` is not deterministic, if you try this code you will see it :

        for (int i = 0; i < 100; i++) {
            ZonedDateTime now1 = ZonedDateTime.now();
            ZonedDateTime now2 = ZonedDateTime.now();
            boolean equals = now1.equals(now2);
            System.out.printf("%s : %s == %s\n", equals, now1, now2);
            Thread.sleep(5L);
        }

```
java version "15.0.2" 2021-01-19
Java(TM) SE Runtime Environment (build 15.0.2+7-27)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.2+7-27, mixed mode, sharing)
```

**Comment by straumat** [comment] 2021-04-16 21:40
@eRfO but in my code, i do call my equal methods that does : `equals = ((ZonedDateTime) object1).isEqual((ZonedDateTime) object2); ` Do you think it's still the problem ? 
[source](https://github.com/cassandre-tech/cassandre-trading-bot/blob/7d9be8b529f4e4049ce343328b1e542737e0cfdc/spring-boot-starter/autoconfigure/src/main/java/tech/cassandre/trading/bot/util/java/EqualsBuilder.java#L37)

**Comment by eRfO** [comment] 2021-04-16 21:45
@straumat yes, I do. If you try to change the test code with `isEqual` method the result is, again, not deterministic.

**Comment by straumat** [comment] 2021-04-16 21:50
@eRfO what do you think I should change ?

**Comment by eRfO** [comment] 2021-04-16 22:18
@straumat I think that you should add other fields in TickerDTO `equals` method or you could set timestamp when you map the xchange Ticker object with yours only if `null`.

**Comment by straumat** [comment] 2021-04-16 22:24
@eRfO Ok. i will study this solution but I always prefer to reproduce the problem before fixing it. Is it possible for you to run my test project with a JDK11 ?

**Comment by eRfO** [comment] 2021-04-16 22:27
@straumat yes, i will do a test with jdk 11, i will let you know.

**Comment by straumat** [comment] 2021-04-18 20:30
@eRfO Hi! maybe I know what's happening. Are you asking a lot of currency pairs?

**Comment by eRfO** [comment] 2021-04-19 11:06
@straumat Hi! No, I just asking for one currency pair. Why are you still in doubt about the problem? We have established that the comparison with the `ZonedDateTime.now()` is not deterministic, you can try using the simple test that I posted. Furthermore, I think that insert a code inside a simple getter method to return data when that is null is not a best practice.

**Comment by straumat** [comment] 2021-04-19 19:07
@eRfO well... before fixing a problem, I always try to reproduce it in a unit test. I think it's not bad practice as that field is mandatory for me and I retrieve it from an external source. 
From my point of view, I still don't get why the same code works on my computer and not on yours. I will add the other fields if I don't find another solution but my idea is first to reproduce in the test then fix it.
I've updated all the libraries, can you make a last try with `4.2.1-SNAPSHOT` please?  (the snapshot will be available in 20 minutes from now).

**Comment by eRfO** [comment] 2021-04-19 20:00
@straumat I will try with the new version. In the meantime, I prepared a simple test to reproduce the problem.

``` Java
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import tech.cassandre.trading.bot.dto.market.TickerDTO;
import tech.cassandre.trading.bot.dto.util.CurrencyPairDTO;

import java.util.LinkedHashMap;
import java.util.Map;

import static tech.cassandre.trading.bot.dto.util.CurrencyDTO.BTC;
import static tech.cassandre.trading.bot.dto.util.CurrencyDTO.EUR;

public class TickerTimestampTest {

    private static Logger logger = LoggerFactory.getLogger(TickerTimestampTest.class);

    @Test
    public void whenTimestampIsNullTest() throws InterruptedException {
        final Map<CurrencyPairDTO, TickerDTO> previousValues = new LinkedHashMap();
        int count = 0;
        for (int i = 0; i < 100; i++) {
            TickerDTO newTicker = TickerDTO.builder().currencyPair(new CurrencyPairDTO(BTC, EUR)).build();
            TickerDTO oldTicker = previousValues.get(newTicker.getCurrencyPair());
            if (!newTicker.equals(oldTicker)) {
                logger.debug("TickerFlux - New ticker received : {}", newTicker);
                previousValues.put(newTicker.getCurrencyPair(), newTicker);
            } else {
                count++;
            }
            Thread.sleep(100L);
        }
        logger.info("Count: {}", count);
        Assertions.assertEquals(0, count);
    }

}
```

this testifies to the non-deterministic nature of the code.

**Comment by eRfO** [comment] 2021-04-19 20:15
@straumat I changed the version to `4.2.1-SNAPSHOT` but the equals method is the same. What change have you made?

**Comment by straumat** [comment] 2021-04-19 20:19
@eRfO I did not change the equals method yet. But I upgraded lots of libraries (spring, reactor), I set parameters to the schedule threadpools. Now, I will integrate your tests to fix the problem.
I'm still so surprised that the same code have different results on your computer and mine. It also works for @Tempys

**Comment by eRfO** [comment] 2021-04-19 20:40
@straumat I understood that @Tempys also had the same problem, he wrote this https://github.com/cassandre-tech/cassandre-trading-bot/issues/544#issuecomment-821563519. You shouldn't be surprised that the same code have different results, is in the nature of non deterministic code, that's the point!

**Comment by straumat** [comment] 2021-04-21 20:16
@eRfO Hi, thanks a lot for the tests. I inserted it in my tests and it never fails on my computer. Does it fail every time on yours? Thanks for the help and sorry for the delay.

**Comment by eRfO** [comment] 2021-04-21 21:16
@straumat Hi, yes it fails every time on my computer.

**Comment by straumat** [comment] 2021-05-02 15:17
@eRfO Hi i made a test with JDK14 and it works well. Besides, even if ZonedDatetime.now returns the same value one time, it should not always do that so you should receive, at least, some tickers. Were you able to make another try ? Thanks

**Comment by straumat** [comment] 2021-05-06 18:53
The equals has been removed with issue https://github.com/cassandre-tech/cassandre-trading-bot/issues/585

**Closed by straumat** 2021-05-06 18:53 UTC
Labels: bug, help wanted
