### ISSUE TITLE
Position not closed - Invalid quantity

### ISSUE THREAD

**Issue by sebasira** [cassandre-tech/cassandre-trading-bot#852] opened 2021-12-20 22:18 UTC
**Release number**
v5.0.7-SNAPSHOT

**Describe the bug**
When trying to close a `Position`, I get the following message:

> s.PositionServiceCassandreImplementation : Position 2 not closed: TradeService - Error calling createMarketOrder for 0.00040000 BTC/USDT: Invalid quantity. (HTTP status code: 400)

I have sufficient amount to sell

**Expected behavior**
I would expect the `Position` to be closed

**Screenshots**
This is how the `Position` looks like in the DB
<img width="606" alt="Screen Shot 2021-12-20 at 19 10 01" src="https://user-images.githubusercontent.com/11217669/146839397-444e4ba7-1cf7-4cd3-ab3f-49637f8f7037.png">

**Additional context**
I'm using **Binance** Exchange. When trying to create the `Position` I was getting error saying something about the **LOT_SIZE**:

> .t.b.s.TradeServiceXChangeImplementation : TradeService - Error calling createMarketOrder for 0.000408 BTC/USDT: Filter failure: LOT_SIZE (HTTP status code: 400)

And several others like this, with different decimals. So I try to reduce the decimal places to 5, and the order was created for `0.00040 BTC`.

I was also having the same error before with 8 decimal places, I reduce it to 6 and create an other few days ago, and then I need to reduce it to 5 for the order to be created.

**Comment by sebasira** [comment] 2021-12-20 22:28
I've found this: https://github.com/ccxt/ccxt/issues/3604. (It's 3 years old)

According to it:

> The `Invalid quantity` says that your order amount is below minumum.

Which is odd, because last week I can successfully sell `0.00037000 BTC`,

**Comment by sebasira** [comment] 2021-12-21 13:33
More info on this. These are **[Trade Rules](https://www.binance.com/en/trade-rule)** from the Binance site:

```
BTC/USDT
Minimum Trade Amount
0.00001 BTC
Min Amount Movement
0.00001 BTC
Min Price Movement
0.01 USDT
Minimum Order Size
10 USDT
Maximum Market Order Amount
142.73116375 BTC
```

I think my trade is within those rules

**Comment by sebasira** [comment] 2021-12-24 15:53
I put the real credentials on my debug environment to see if I can put some light into this. And I here's what I've found:

The error occurs at method `createMarketOrder()` in the `TradeServiceXChangeImplementation` class, here's the related block of code:

```java
private OrderCreationResultDTO createMarketOrder(final GenericCassandreStrategy strategy,
                                                     final OrderTypeDTO orderTypeDTO,
                                                     final CurrencyPairDTO currencyPair,
                                                     final BigDecimal amount) {
  try {
      // Making the order.
      MarketOrder m = new MarketOrder(utilMapper.mapToOrderType(orderTypeDTO),
              amount.setScale(currencyPair.getBaseCurrencyPrecision(), FLOOR),
              currencyMapper.mapToCurrencyPair(currencyPair),
              getGeneratedOrderId(),
              null);
      logger.debug("Sending market order: {} - {} - {}", orderTypeDTO, currencyPair, amount);
```

The problem is at:

```java
 amount.setScale(currencyPair.getBaseCurrencyPrecision(), FLOOR),
```


Debugging I can see that  `currencyPair.getBaseCurrencyPrecision()` is ZERO, so when setting scale, the result amount is **ZERO**, so it tries to create and order for 0 BTC and thus the **Invalid Quantity**.

What I do not know is why is that.

Here's a screenshot so you can see it:
<img width="440" alt="Screen Shot 2021-12-24 at 12 47 48" src="https://user-images.githubusercontent.com/11217669/147363001-8f2cb3cf-e440-47ac-b19e-54baf7aed4d6.png">

I would recommend a change to help in the future... The first thing I did was enable DEBUG level logging, and this line was printted (according to the last line of the above code):

> TradeServiceXChangeImplementation : Sending market order: ASK - BTC/USDT - 0.00040000

So I though the quantity was correct. But as an operation is done on the amount (the setScale) maybe it would be helpful to print that amount instead. In this case it would have printed `Sending market order: ASK - BTC/USDT - 0.00000000` and it would be more clear where the error is.

**Merry Cryptmas** *from Argentina!*

**Comment by sebasira** [comment] 2021-12-25 13:30
I leave an image where we can see that the `PositionDTO` has the correct values for precision, while the `TickerDTO` does not and that is the problem:

<img width="883" alt="Drawing" src="https://user-images.githubusercontent.com/11217669/147385932-85db0c34-2892-4d3b-a876-d7c30280c987.png">


This corresponds to `GenericCassandreStrategy` class, the line **470** in method `updatePositionsWithTickersUpdates`. Here's a link to that https://github.com/cassandre-tech/cassandre-trading-bot/blob/105d548d0cc50a81a2b04e7dcabdfeb3cc2e7e8e/spring-boot-starter/autoconfigure/src/main/java/tech/cassandre/trading/bot/strategy/GenericCassandreStrategy.java#L470

**Comment by straumat** [comment] 2021-12-25 23:19
@sebasira Hi and merry xmas from France! 
I added a better log:
```
            logger.debug("Sending market order: {} - {} - {}",
                    orderTypeDTO,
                    currencyPair,
                    amount.setScale(currencyPair.getBaseCurrencyPrecision(), FLOOR));
```
What other improvement do you advise?

**Comment by sebasira** [comment] 2021-12-26 00:25
Thank you!

What I think should be done is fix the ZERO precision that's the actual problem.

The **baseCuurrencyPrecision** and **quoteCuurrencyPrecision** are both zero, after 

```java
tickers.get(positionDTO.getCurrencyPair())
```

from the line of code referenced above. That's what's causing the real issue here, that sends a transaction of zero crypto which is an Invalid Quantity

**Comment by sebasira** [comment] 2021-12-26 02:30
I've found where the error comes from. 

It's where the `Ticker` is converted to a `TickerDTO`. This is done by the `TickerMapper`. The mapper implementation is generated by **MapStruct** and this is how I see the implementation `TickerMapperImpl` (As this is auto-generated by MapStruct maybe what I see it is not the same as what you see). This is how I see the implementation:

```java
@Override
public TickerDTO mapToTickerDTO(Ticker source) {
    if ( source == null ) {
        return null;
    }

    TickerDTOBuilder tickerDTO = TickerDTO.builder();

    tickerDTO.currencyPair( currencyMapper.mapToCurrencyPairDTO( source.getInstrument() ) );
    tickerDTO.open( source.getOpen() );
```

The important part here is `currencyMapper.mapToCurrencyPairDTO( source.getInstrument() )`, so let's see that method:

```java
default CurrencyPairDTO mapToCurrencyPairDTO(Instrument source) {
    final CurrencyPair cp = (CurrencyPair) source;
    CurrencyDTO base = new CurrencyDTO(cp.base.getCurrencyCode());
    CurrencyDTO quote = new CurrencyDTO(cp.counter.getCurrencyCode());
    return CurrencyPairDTO.builder().baseCurrency(base).quoteCurrency(quote).build();
}
```

This method uses the `CurrencyPairDTO` **Builder** which calls the all-argument constructor with zero value for **baseCurrencyPrecision** and **quoteCurrencyPrecision**. That's the problem!

The way I managed to solve this locally is by modifying the `CurrencyPairDTO` class by removing the `@Value` annotation from **Lombok** and replacing it with `@Data` (or `@Getter`) and then this:

```java
/** The base currency precision. */
@Builder.Default
int baseCurrencyPrecision = DEFAULT_CURRENCY_PRECISION;

/** The quote currency precision. */
@Builder.Default
int quoteCurrencyPrecision = DEFAULT_CURRENCY_PRECISION;
```

This way this is the default value for those properties when using the **Builder**

Please let me know what you think about this. What seems strange for me is that this problem should affect every body using this

**Comment by sebasira** [comment] 2021-12-26 03:02
Another approach could be to mark the all-args constructor with **@Tolerate**.

From the official Lombok documentation:

> Note that if both `@Builder` and `@Value` are on a class, the package private allargs constructor that `@Builder` wants to make 'wins' over the public one that `@Value` wants to make. You can mark any constructor or method with @lombok.experimental.Tolerate to hide them from lombok.

**Comment by xblaatx** [comment] 2021-12-26 11:59
@sebasira. I was working on currency precisions. But i'm still on holiday.

Because Xchange doesn't set the precision for currencies it is our responsibility to do it.  
I provided baseCurrencyPrecision and quoteCurrencyPrecision in the CurrencyPairDTO. These can be set in the getRequestedCurrencyPairs() method where we specify the currency pair.

The problem is. With positions when ticker updates are received from Xchange marketDataService. those tickers does not include any properties with precision. so we need need to set it in the CurrencyPairDTO somewhere. my best guess is in the TickerFlux getNewValues method.

What do you think?

**Comment by sebasira** [comment] 2021-12-26 12:33
Hi @xblaatx! Happy holidays!

Indeed, I was looking into the `TickerFlux` **getNewValues** method and that led me to the `TickerMapper`, which finally led me to the `CurrencyPairDTO` and what I notice above.

To be more specific: The `TickerFlux` calls **marketService.getTickers**, this method is implemented in the class `MarketServiceXChangeImplementation` which uses the `TickerMapper` in:

```java
TickerDTO t = tickerMapper.mapToTickerDTO(marketDataService.getTicker(currencyMapper.mapToCurrencyPair(currencyPair)));
```

What I do not like about:

```java
/** The base currency precision. */
@Builder.Default
int baseCurrencyPrecision = DEFAULT_CURRENCY_PRECISION;

/** The quote currency precision. */
@Builder.Default
int quoteCurrencyPrecision = DEFAULT_CURRENCY_PRECISION;
```

Is that we are using the default precision that is not always the desired one. I now **Binance** has an API endpoint  where we can get the precision of each pair, but I do not know if that exists across all exchanges so I discarded that.

Another solution I'm thinking is that the `TikcerMapper` uses the `CurrencyPairDTO` as argument, like this:

```java
@Mapping(source = "currencyPair", target = "currencyPair")
TickerDTO mapToTickerDTO(Ticker source, CurrencyPairDTO currencyPair);
```
This way we won't be using the `default CurrencyPairDTO mapToCurrencyPairDTO(Instrument source)` which has the @Builder issue

**Comment by sebasira** [comment] 2021-12-26 12:41
I'm trying to implement and test what I've stated but as I do not know much about streams I do not know how to make the call in 

```java
return tickers.stream()
                    .map(tickerMapper::mapToTickerDTO)
```

**Comment by sebasira** [comment] 2021-12-26 13:14
The way I manage to re-write it is like this:

**TickerMapper**
```java
@Mapping(source = "currencyPair", target = "currencyPair")
TickerDTO mapToTickerDTOWithCurrency(Ticker source, CurrencyPairDTO currencyPair);
```

And the re-write without using streams:

```java
final List<Ticker> tickers = marketDataService.getTickers(params);
LinkedHashSet<TickerDTO> tickerDTO = new LinkedHashSet<>();
for (Ticker ticker : tickers) {
    CurrencyPairDTO currencyPair = currencyPairs.stream().filter(item->item.equals(new CurrencyPairDTO(ticker.getInstrument()))).findFirst().get();
    TickerDTO t = tickerMapper.mapToTickerDTOWithCurrency(ticker, currencyPair);
    logger.debug(" - New ticker: {}", t);
    tickerDTO.add(t);
}
return tickerDTO;
```

I leave it here and not submit a PR so you can take a look into it. As I'm not using streams because I do not know how to do it.

**Comment by straumat** [comment] 2022-01-01 21:57
@sebasira thx for the pull request. But as there is no unit test, can you try it with your bot in production if I merge it?

**Comment by straumat** [comment] 2022-01-01 23:22
@sebasira & @xblaatx : Ok, I'm not sure yet if I get the problem right but I think of something. 
In [closePosition](https://github.com/cassandre-tech/cassandre-trading-bot/blob/73b199aa77986cbf1580d3ea1647699b05289743/spring-boot-starter/autoconfigure/src/main/java/tech/cassandre/trading/bot/service/PositionServiceCassandreImplementation.java#L163), if I use `PositionDTO.getCurrencyPair()` when I call `createSellMarketOrder` instead of using `ticker.getCurrencyPair()`?

Don't you think this will avoid the mapstruct problem?

**Comment by xblaatx** [comment] 2022-01-02 14:16
> @sebasira & @xblaatx : Ok, I'm not sure yet if I get the problem right but I think of something. 
> In [closePosition](https://github.com/cassandre-tech/cassandre-trading-bot/blob/73b199aa77986cbf1580d3ea1647699b05289743/spring-boot-starter/autoconfigure/src/main/java/tech/cassandre/trading/bot/service/PositionServiceCassandreImplementation.java#L163), if I use `PositionDTO.getCurrencyPair()` when I call `createSellMarketOrder` instead of using `ticker.getCurrencyPair()`?
> 
> Don't you think this will avoid the mapstruct problem?

This indeed avoids the mapstruct problem. Thx.
I will change the pull request tomorrow.

**Comment by straumat** [comment] 2022-01-02 20:33
@sebasira & @xblaatx I think what I propose won't fix your issue. I try to make a new comment later tonight on how to fix it.

**Comment by straumat** [comment] 2022-01-02 20:48
@sebasira & @xblaatx  First of all, I never faced this issue, in my tests, this is what I do:
- Binance: long 0.02 ETH/USDT.
- Coinbase: long 20 ADA/USDC.
- Kucoin: long and short 0.002 BTC/USDT plus long 1 UNI/USDT.


How is it possible that I don’t face the same issue as you do?

**Comment by sebasira** [comment] 2022-01-02 23:32
I think this happens only when the `@Strategy` extends `BasicTa4jCassandreStrategy`

**Comment by sebasira** [comment] 2022-01-03 01:04
I'm confused... if it was solve by https://github.com/cassandre-tech/cassandre-trading-bot/commit/42648c206e1ab2ac47670bfb76383cda6b55e172, then the PR is not needed, right?

**Comment by straumat** [comment] 2022-01-03 08:08
@sebasira i'm not sure what I did is enough :( 
To be sure, i need to understand why i don't face the problem you have with my testing bots as I said in https://github.com/cassandre-tech/cassandre-trading-bot/issues/852#issuecomment-1003772971

**Comment by straumat** [comment] 2022-01-03 10:22
following a chat on discord with @xblaatx : fields should be added in PositionDTO table to store the precision of the currency pair created by the user for his positions.

**Comment by straumat** [comment] 2022-01-03 21:55
@sebasira & @xblaatx First working solution (I hope)!
I just pushed a fix on branch https://github.com/cassandre-tech/cassandre-trading-bot/tree/issue_852
I now save base and quote currency precisions in the position table. I think this will solve the issue.
as it implies a new database structure change, this will only be merged in `5.0.8` (`5.0.7` should be out this week if all goes well). 

If you want to test it, you will have to build your own 5.0.7-SNAPSHOT. To do it, download the branch and run: `mvn install -Dgpg.skip -Dmaven.test.skip=true`

Waiting for your feedbacks!

**Comment by sebasira** [comment] 2022-01-04 13:02
Thank you for your work! I'll test it in a couple of days to provide feedback.

**Comment by straumat** [comment] 2022-01-06 18:09
I forgot to give a link to the test I wrote to validate the change: [https://github.com/cassandre-tech/cassandre-trading-bot/blob/323aaa72ecf3a7389851c825b147db8982a55b29/spring-boot-starter/autoconfigure/src/test/java/tech/cassandre/trading/bot/test/issues/v5_x/v5_0_7/Issue852Test.java#L46](https://github.com/cassandre-tech/cassandre-trading-bot/blob/323aaa72ecf3a7389851c825b147db8982a55b29/spring-boot-starter/autoconfigure/src/test/java/tech/cassandre/trading/bot/test/issues/v5_x/v5_0_7/Issue852Test.java#L46)

**Comment by straumat** [comment] 2022-01-16 20:15
I close it for now, reopen if a problem occurs

**Closed by straumat** 2022-01-16 20:15 UTC
Labels: bug
