### ISSUE TITLE
Position getDescription() bad Currency

### ISSUE THREAD

**Issue by sebasira** [cassandre-tech/cassandre-trading-bot#850] opened 2021-12-16 15:36 UTC
**Release number**
v5.0.6

**Describe the bug**
I think that the currency displayed in the log statement when a `Position` is closed is incorrect. I had a `Position` of around *0.00036 BTC* and when it was closed, the log said:

> Position closed : Long position n??1 (rules : 1.0 % gain) on BTC/USDT - Closed - Gains: 0.1911753000000000 USDT (1.06 %) / Fees: 0.01816711 BTC

The code for that statement is:

```java
logger.info("Position closed : {}", position.getDescription());
```

I think the `Currency` of the fee should be **USDT** in this case, or else this was the worst trade in my life! LOL

**Comment by straumat** [comment] 2021-12-16 17:04
@sebasira from what I can see, it seems that it's the same issue than #846. In fact, I have only one fee field in GainDTO (I make the sum of the fees of the two trades) but I did not take into account that the two trades could have different currency. 

I need to udapte GainDTO to have two fees fields. Don't you think ?

**Comment by sebasira** [comment] 2021-12-16 20:31
I'm not completely sure if it's the same. The `Position` is indeed the same.

If you look in the post you mention the table has the fee expressed in BTC and the fee is 0.00000037 BTC. At the sell price aprox 49000 USDT/BTC that fee become 0.018 USDT.

The `getDescription()` method give us:

> Long position n??1 (rules : 1.0 % gain) on BTC/USDT - Closed - Gains: 0.1911753000000000 USDT (1.06 %) / Fees: 0.01816711 BTC

So the fee value corresponds to USDT, but is expressed in BTC. What I mean is that that message should end like:

> 0.018 USDT

or 

> 0.00000037 BTC

**Comment by straumat** [comment] 2021-12-25 22:51
@sebasira in the latest snapshot, fees are now improved in `GainDTO` object. There is a list of fees. Can you tell me about it ?

**Comment by straumat** [comment] 2022-01-01 21:44
Duplicate of #846

**Closed** 2022-01-08 21:21 UTC
Labels: bug
