### ISSUE TITLE
Position not closed - Account has insufficient balance

### ISSUE THREAD

**Issue by sebasira** [cassandre-tech/cassandre-trading-bot#846] opened 2021-12-12 00:44 UTC
**Release number**
v5.0.6

**Describe the bug**
I get this error when trying to close a `Position`

> 2021-12-12 00:34:18.444 ERROR 7746 --- [cassandre-flux-3] s.PositionServiceCassandreImplementation : Position 1 not closed: TradeService - Error calling createMarketOrder for 0.00037000 BTC/USDT: Account has insufficient balance for requested action. (HTTP status code: 400)

As I was not able to test in **dry mode** because of #843, I've decided to test this out with little real money. I'm using **Binance** exchange, I put *20 USDT* in the account and buy some *BTC* with a `LongPosition`. I've set stop gain at **1%** just to test and the `Position` could not be closed because of the error above.

I don't know why it says I have not enough balance, right now the amount in the wallet is 0.00039029 BTC, so I should be able to sell 0.00037000.

**To Reproduce**
I guess it should be enough to open a LongPosition with a Binance account

**Expected behavior**
I would expect the `Order` to be created and the `Position` closed

**Screenshots**
This is how the `Position` looks in the DB:
<img width="816" alt="Screen Shot 2021-12-11 at 21 40 24" src="https://user-images.githubusercontent.com/11217669/145696247-6112fd7c-f251-47fc-90c0-72f86867cb52.png">

**Additional context**

**Comment by sebasira** [comment] 2021-12-12 01:05
I'm sorry... I must correct my self. The balance is indeed inssuficient. (I was looking at the total amount BTC + USDT which was 0.00039 BTC)

I looked again in the Exchange and I've got 0.00036963 BTC so I can not sell 0.00037000 BTC.

So I've started investigating and the difference is because of the **fee**. I looked at the order in Exchange  and I was for 0.00037000 BTC, with a fee of 0.00000037 BTC so my net amount is 0.00036963 BTC.

I started looking around in the DB and the **fee** is present in the `TRADE` table so I guess it's not used when closing the `Position`.

Here's the `Trade` for the buying `Order` of the `Position`:
<img width="935" alt="Screen Shot 2021-12-11 at 22 01 53" src="https://user-images.githubusercontent.com/11217669/145696620-be721895-1591-46af-8a2c-8c04cf07e8a5.png">

**Comment by straumat** [comment] 2021-12-12 20:56
@sebasira  Hi, from what I understand, you created a 0.00037000 BTC/USDT position but when you take a look at the exchange, there is only 0.00036963 BTC because of the fees.
I need to investigate but from what I have seen on other exchanges, when you send an order to buy 0.00037000 BTC, you get 0.00037000 BTC and you also have fees but you should get the amount you wanted, thats is to say 0.00037000 BTC.
Seems you ahve to keep some BTC to pay fees... i really need to investigate because I did not notice this before.

**Comment by straumat** [comment] 2021-12-12 21:15
@sebasira I will download my Binance production database tomorrow night and see what I have in orders/trades and if I had closing error

**Comment by straumat** [comment] 2021-12-12 21:45
@sebasira Maybe there is an explanation, you use all your USDT to create the position so, as you have nothing left except BTC, when you try to sell, it can use USDT and try to take fees in BTC, what do you think ?

**Comment by sebasira** [comment] 2021-12-12 22:36
Thank you for looking into this.

What you suggest is possible. I really can’t tell because this is the first time I test it in a real environment.

I will force close the position and create a new one with a lower amount so I can confirm you thought.

**Comment by sebasira** [comment] 2021-12-12 22:40
Also if this depends on the exchange to make it more generic it could try with the amount from the Position. But if the error is the insufficient balance it could tray with the amount minus the fee

**Comment by straumat** [comment] 2021-12-13 19:57
@sebasira this is what I have in database for my Binance bot.

When I query a closed position: `select ID, TYPE, CURRENCY_PAIR, AMOUNT_VALUE, AMOUNT_CURRENCY, STATUS, fk_opening_order_id, fk_closing_order_id from POSITIONS where ID = 1;`

This is the data I get:
```
 id | type | currency_pair | amount_value | amount_currency | status | fk_opening_order_id | fk_closing_order_id 
----+------+---------------+--------------+-----------------+--------+---------------------+---------------------
  1 | LONG | ETH/USDT      |   0.02000000 | ETH             | CLOSED |                   1 |                  11

```

when I check the opening order : `select id, order_id, type, amount_value, amount_currency from orders where id = 1;`

This is the data I get:
```
 id |  order_id  | type | amount_value | amount_currency 
----+------------+------+--------------+-----------------
  1 | 6285774074 | BID  |   0.02000000 | ETH

```

When i check the trade : `select id, trade_id, type, amount_value, amount_currency, fee_value, fee_currency from trades where fk_order_id = 1;`
This is the data I get:
```
 id | trade_id  | type | amount_value | amount_currency | fee_value  | fee_currency 
----+-----------+------+--------------+-----------------+------------+--------------
  1 | 637761655 | BID  |   0.02000000 | ETH             | 0.00002000 | ETH

```

when I check the closing order : `select id, order_id, type, amount_value, amount_currency from orders where id = 11;`

This is the data I get:
```
 id |  order_id  | type | amount_value | amount_currency 
----+------------+------+--------------+-----------------
 11 | 6331002853 | ASK  |   0.02000000 | ETH

```

When i check the trade : `select id, trade_id, type, amount_value, amount_currency, fee_value, fee_currency from trades where fk_order_id = 11;`
This is the data I get:
```
 id | trade_id  | type | amount_value | amount_currency | fee_value  | fee_currency 
----+-----------+------+--------------+-----------------+------------+--------------
 11 | 641414330 | ASK  |   0.02000000 | ETH             | 0.08163140 | USDT

```

It's strange as I'm nearly sure, that, when I started the bot, I only had USDT and no ETH on Binance... si I don't really know how they manage, on position number 1 to take ETH fees... and if they did so, how come they managed to sell 0.02 ETH

**Comment by sebasira** [comment] 2021-12-20 22:54
I was looking in **Binance** app, in the Order History section.

What I notice is that the fee is in the same Currency as the Trade

For example, I bought 0.00037 BTC and the fee was 0.00000037 BTC. Then I sell those BTC and I get 18USDT from them, and the fee was 0.018USDT. 

Also, when I commit the first `Position`, I'm 100% sure I only had **USDT**. So as it can not take the fee from the BTC I own (because I own zero), they took it from my trade, and that's why I only get 0.0003697 insted of 0.00037 BTC.

So when the base Currency has no balance to supply the fee, it took it from the Trade, in the same Currency of the Trade.

For me, it's ok to close this issue.

It's a border condition, because when I started I only have one of the two Currencies, so it can not take the fee of the base currency.

I don't know if Cassandre could/should solve this issue, maybe it's up to the developer to manage this situation. Check the balance before opening/closing a `Position` and if this scenario is detected, change the amount of the market order

**Comment by straumat** [comment] 2021-12-21 08:25
@sebasira thanks a lot for looking in details. What I'm working on is to remove getFees in GainDTO to set a new method that return a list of fees. Because, I cannot guarantee that the opening order fees currency will be the same that the closing order fees currency. What do you think ?

**Comment by sebasira** [comment] 2021-12-21 11:43
I agree with you. When you said:

>  I cannot guarantee that the opening order fees currency will be the same that the closing order fees currency

Actually it will never be. Let's assume the BTC/USDT pair. When you open a Long position, you buy BTC and the fee is in BTC. When you sell BTC (you buy USDT) the fee is USDT. Always!

Then what we've been discussing here is where that fee comes from. If the balance is insufficient to charge the fee from your wallet, then the fee (expressed **ALWAYS** in the currency you are buying) is taken from the trading amount.

**Comment by sebasira** [comment] 2021-12-21 13:10
What I like about a list of fees, is that when a Position is closed there 2 fees involve. The buying fee and the selling fee

**Comment by straumat** [comment] 2022-01-01 21:42
@sebasira in the `5.0.7-SNAPSHOT`, fees are now improved in `GainDTO` object. There is a list of fees. Can you tell me what you think about it? Thx

**Comment by straumat** [comment] 2022-01-01 21:44
Duplicate of #850

**Closed** 2022-01-06 17:39 UTC
Labels: bug, duplicate

**Comment by kiranpl** [comment] 2022-02-12 07:29
@straumat, not sure why this bug is not fixed and marked as duplicate of #850 as I also have the same issue as @sebasira.

I am running my bot using Binance with a small amount of real funds of $77. The bot opened a position for FLUX/USDT for **14 FLUX** coins (28.07 USDT) but when the order was executed, the available amount is: **13.98600000 FLUX** as a fees of **0.014 FLUX** was charged. Now when the bot tries to close the Position, it can't as the amount of 14 FLUX is not available. I get the same error as below:

`Error calling createMarketOrder for 14.00000000 FLUX/USDT: Account has insufficient balance for requested action`

Sorry if I am missing something here, please suggest if I need to make any changes to the config to make it work.

**Comment by sebasira** [comment] 2022-02-12 12:08
Hi! 

From my point of view, this is a border condition that could only happen once, when going all-in in a position and not having more coins of the base or quote currency. What I decided to do, because I didn't get the time to look into this deeply, is not to use the 100% of my coins and leave a tiny amount for fees and to avoid this situation.

What I guess could be simple a solution is not to use the amount from the `Position`, when closing it, but to use the amount minus the fee. This would (in time) leave a very tiny amount in the base currency, but it's really very little. 

The other solution that will not involve changes to the code is to be always sure to have enough base and quote currency for the fees

**Comment by kiranpl** [comment] 2022-02-12 12:46
Sebastian,

I don't think that this is a one-off case at least in my case. I can see
that I have enough USDT (quoted currency). The issue here as I understand
is that the amount in Close order (14) and the amount bought earlier
doesn't match as the fees has been deducted from that amount. I believe
this is an issue specific to Binance but will happen for every Position.

**Comment by sebasira** [comment] 2022-02-12 14:02
What I've learnt from using Binance (I don't know about others ) is that the fee is **always** in the base currency. If you buy BTC, the fee is in BTC, if you buy FLUX, the fee is in FLUX. If you sell them (buy USDT) the fee is in USDT

When some open up an account and start trading, most of the time we start by depositing USDT in our account, so the only currency available is USDT.

When you use them to buy another currency, in your case FLUX, Binance charges the fee in FLUX (as explained above), but you don't have FLUX in your account, you only have USDT, so the fee is taken from the amount you have bought. So it's like two operations happen in the same time. You definitely buy 14 FLUX, and them Binance charges the fee.

Cassandre does not know about this, so unless you check your balance after the operation you won't know that the fees was consumed from your trade. Cassandre thinks you have the amount you have bought.

So, one easy way to avoid this is buying FLUX (in your case) directly from Binance, A small amount, just to cover the fees when Cassandre is working. And then after that *manual operation* start trading with Cassandre

**Comment by straumat** [comment] 2022-02-13 15:12
@kiranpl HI. Depending on exchanges, you indeed to always have some currency left to pay the fees... I think your problem comes from here. That's why I developed some canSell and canBuy methods with a parameter telling how much money left you would have after the operation.
